# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-03 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desplash', '0002_remove_image_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_url',
            field=models.TextField(blank=True),
        ),
    ]
