# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-04 06:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desplash', '0003_image_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='post_date',
            new_name='date_posted',
        ),
    ]
