# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-04 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desplash', '0010_auto_20180504_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.AddField(
            model_name='image',
            name='category',
            field=models.ManyToManyField(to='desplash.Category'),
        ),
    ]
