# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-04 07:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('desplash', '0006_remove_image_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='desplash.Category'),
        ),
    ]
