# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-04 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desplash', '0007_image_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='category',
        ),
        migrations.AddField(
            model_name='image',
            name='category',
            field=models.ManyToManyField(blank=True, to='desplash.Category'),
        ),
    ]
