# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-06 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desplash', '0013_auto_20180504_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='category',
            field=models.ManyToManyField(blank=True, to='desplash.Category'),
        ),
        migrations.AlterField(
            model_name='image',
            name='location',
            field=models.ManyToManyField(blank=True, to='desplash.Location'),
        ),
    ]
